language: minimal
services:
  - docker

env:
  COMPOSE_VERSION="1.24.1"

# Install compose & download tarpaulin test image for rest-api
install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - yes | sudo mv docker-compose /usr/local/bin

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_JOB_ID

script:
  # Run compose file in test/docker-compose.yaml 
  - cargo fmt -- --check
  - yes | docker-compose -f test/docker-compose.yaml up --exit-code-from test-rest-api 
    